Repository CrayonAS/AutomationEasy, pull requests merged in 2018-12, with the labels that each got.

#38 Adds support for provisioning users to Azure Active directory. Minor bugfixes.
  deploy/user-management/Modules/User.Management.Automation/Functions/New-UMUser.ps1
Labels: bug, documentation, enhancement

#39 New runbooks to handle syncing/updating modules in AA and on hybrid workers
  .github/PULL_REQUEST_TEMPLATE.md
  deploy/azure-automation/Runbooks/Update-AAHybridWorkerModules.ps1
  deploy/azure-automation/Runbooks/Update-AAModules.ps1
  docs/Features/Azure-Automation/Runbooks/Update-AAHybridWorkerModules.md
  docs/Features/Azure-Automation/Runbooks/Update-AAModules.md
Labels: enhancement

#41 Adds GIF-animated Plaster demo to README and documentation
  README.md
  docs/Contributing.md
  docs/Deploy/index.md
  docs/img/plaster_demo.gif
  docs/index.md
Labels: documentation
